

apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  selector:
    app: wordpress
    tier: mysql
  ports:
    - port: 3306
                 ### targetport defaults to the same as port
    ### default will be clusterIp 